apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
  namespace: development
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl
              command: ["sh", "-c", "curl http://nginx-service"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1