apiVersion: batch/v1
kind: Job
metadata:
  name: internal-port-job
  namespace: development
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: ["sh", "-c", "curl http://nginx-service"]
      restartPolicy: Never
  backoffLimit: 4