apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacman-kubernetes.fullname" . }}
  labels:
    {{- include "pacman-kubernetes.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "pacman-kubernetes.selectorLabels" . | nindent 4 }}
